## *Shift Academy Data Science Bootcamp Batch 10 - Remake* ##

### *Introduction to Numpy and Pandas* ###

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create list, array, dictionary and the label for creating series
thelist = [4, 7, 3, 9, 1]
array = np.array([4, 7, 3, 9, 1])
label = ['First', 'Second', 'Third', 'Fourth', 'Fifth']
dictionary = {'First': 4, 'Second': 7, 'Third': 3, 'Fourth': 9, 'Fifth': 1}

thelistSeries = pd.Series(data=thelist, index=label)
arraySeries = pd.Series(array, label)
dictionarySeries = pd.Series(dictionary)

In [3]:
print(thelistSeries)

First     4
Second    7
Third     3
Fourth    9
Fifth     1
dtype: int64


In [4]:
arraySeries

First     4
Second    7
Third     3
Fourth    9
Fifth     1
dtype: int64

In [5]:
dictionarySeries

First     4
Second    7
Third     3
Fourth    9
Fifth     1
dtype: int64

## *Woke Sip Mantap. Latihan terooos.*

## *Numpy Array* ##

In [7]:
array = np.array([7, 4, 8, 3, 6])
array

array([7, 4, 8, 3, 6])

In [9]:
type(array)

numpy.ndarray

In [10]:
array.dtype

dtype('int64')

## *Create array form list* ##

In [11]:
alist = [9, 5, 8, 6, 3]
anarray = np.array(alist)
anarray

array([9, 5, 8, 6, 3])

## *Create array from matrix* ##

In [12]:
amatrix = [[3,8,5],[8,5,6],[1,4,2]]
anarraymatrix = np.array(amatrix)
anarraymatrix

array([[3, 8, 5],
       [8, 5, 6],
       [1, 4, 2]])

## *Create array from zeros* ##

In [13]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

## *Create array from ones*

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
#ones with number 6
np.ones(5) * 6

array([6., 6., 6., 6., 6.])

## *Create array with certain range* ##

In [18]:
np.arange(15)
# will be print array 0 - 14. 0 will be the first number, and 14 will be the last. 15 will be exclusive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(7, 15)
# will be print array 7 - 14. 7 will be the first number, and 14 will be the last. 15 will be exclusive

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(1, 15, 2)
# will be print array 1 - 14 and will be jumped for 2 step. 1 will be the first number, and 14 will be the last. 15 will be exclusive

array([ 1,  3,  5,  7,  9, 11, 13])

## *Create array evently divided range* ##

In [31]:
np.linspace(0, 100, 5)
# will be print array from 0 - 100 evently divided to 5 number

array([  0.,  25.,  50.,  75., 100.])

In [38]:
np.linspace(0, 100, 11)
# will be print array from 0 - 100 evently divided to 11 number

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## *Specifying Datatypes* ##

In [43]:
np.linspace(0, 100, 11, dtype = 'int64')
# will be print array from 0 - 100 evently divided to 11 number

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## *Random Normal Distribution* ##

In [50]:
np.random.randn(4, 4)

array([[ 0.99166832, -0.40808867, -1.08104591,  1.01594933],
       [-0.23592164,  0.35560776,  1.69119815,  0.0522259 ],
       [ 0.89264053,  1.36127886, -0.60013366,  0.93225681],
       [-1.68922604,  0.97140287,  1.05658432, -0.05784414]])

## *Random Interger* ##

In [52]:
np.random.randint(5, 50, [3, 4]) 
#low (inclusive) #high (exclusive) #range

array([[43, 47, 23, 28],
       [12, 46, 41, 32],
       [ 9,  8, 40, 44]])

## *Look For* ##

In [53]:
np.lookfor('random')

Search results for 'random'
---------------------------
numpy.random.ranf
    This is an alias of `random_sample`. See `random_sample`  for the complete
numpy.random.PCG64
    BitGenerator for the PCG-64 pseudo-random number generator.
numpy.random.Philox
    Container for the Philox (4x64) pseudo-random number generator.
numpy.random.sample
    This is an alias of `random_sample`. See `random_sample`  for the complete
numpy.random.MT19937
    Container for the Mersenne Twister pseudo-random number generator.
numpy.matlib.rand
    Return a matrix of random values with given shape.
numpy.matlib.randn
    Return a random matrix with data from the "standard normal" distribution.
numpy.random.RandomState
    Container for the slow Mersenne Twister pseudo-random number generator.
numpy.random.Generator.bytes
    bytes(length)
numpy.random.Generator.choice
    Generates a random sample from a given 1-D array
numpy.random.Generator.normal
    Draw random samples from a normal (Gaussian) distr

## *Array Statistic Attribute (random)* ##

In [64]:
arrayrandom = np.random.randint(0, 100, 25)
arrayrandom

array([96, 46, 65, 60, 30, 28, 68, 49, 55,  2, 28, 18, 77, 17, 46, 11, 37,
       90,  0, 30, 58, 38, 78, 69, 17])

In [67]:
arrayrandom.sum()

1113

In [68]:
arrayrandom.min()

0

In [69]:
arrayrandom.max()

96

In [70]:
arrayrandom.mean()

44.52

## *Numpy Attributes* ##
Shape
Reshape
Size

In [72]:
arrayrandom.shape

(25,)

In [73]:
arrayrandom.size

25

In [79]:
reshaped = arrayrandom.reshape(0, 100)
reshaped

ValueError: cannot reshape array of size 25 into shape (0,100)

In [80]:
reshaped.shape

NameError: name 'reshaped' is not defined

## *Indexing and Slicing Array with Condition*

In [82]:
arrayindex = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])

In [83]:
print(arrayindex[arrayindex > 15])

[16 17 18 19 20 21 22 23 24 25]


In [84]:
under_until_ten = (arrayindex <= 10)
print(arrayindex[under_until_ten])

[ 1  2  3  4  5  6  7  8  9 10]


In [86]:
divisible_by_5 = arrayindex[arrayindex % 5 == 0]
print(divisible_by_5)

[ 5 10 15 20 25]


## *Create array from existing data* ##

In [88]:
arrayexist = ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arrayexist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [98]:
array1 = arrayexist[1:3] #start 2 #until number 3
array1

[2, 3]

In [97]:
array1 = arrayexist[2:9] #start 3 #until number 9
array1

[3, 4, 5, 6, 7, 8, 9]

In [99]:
array1 = arrayexist[2:9:3] #start 3 #until number 9 #jump 3 step
array1

[3, 6, 9]

## *Vstack Hstack*

In [101]:
stack1 = ([[1, 1, 1],
           [2, 2, 2],
          [3, 3, 3]])
stack2 = ([[4, 4, 4],
           [5, 5, 5],
          [6, 6, 6]])

In [104]:
#Vstack
np.vstack((stack1, stack2))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [105]:
#Hstack
np.hstack((stack1, stack2))

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])